### ISSUE TITLE
Move to JuliaPerf?

### ISSUE THREAD

**Issue by crstnbr** [JuliaPerf/STREAMBenchmark.jl#10]
@vchuravy: Do you think it would make sense to move this package to JuliaPerf? (Given we have things like Roofline.jl and LIKWID.jl over there.)

**Comment by crstnbr** [comment]
BTW, JuliaPerf needs a logo!

**Comment by vchuravy** [comment]
Sent you an invitation, feel free to move the repo!

**Comment by crstnbr** [comment]
Done.
